project:
  type: website
  output-dir: docs

website:
  title: "web"
  navbar:
    left:
      - href: index.qmd
        text: phd12
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



